from pathlib import Path
import subprocess
import re
import logging
from pyrogram import Client

# Setup logging
logging.basicConfig(level=logging.INFO)

# Constants
PROJECT_FOLDER = Path(__file__).resolve().parent.parent.parent
CHANNEL = "@stewart_github"
REPO_URL = "https://github.com/ilyamiro/stewart"


# Utility Functions
def run_git_command(args, use_shell=False):
    try:
        result = subprocess.run(args, capture_output=True, text=True, shell=use_shell, check=True)
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        logging.error(f"Error running command {args}: {e}")
        return None


def replace_repeated_chars(input_string, char):
    pattern = f"{re.escape(char)}+"
    return re.sub(pattern, char, input_string)


def format_commit_changes(raw_changes):
    change_lines = raw_changes.strip().split("\n")
    formatted_changes = "\n".join([f"• {line.strip()}" for line in change_lines if line.strip()])

    # Apply repeated character replacements
    formatted_changes = replace_repeated_chars(formatted_changes, "+")
    formatted_changes = replace_repeated_chars(formatted_changes, "-")
    formatted_changes = replace_repeated_chars(formatted_changes, " ")
    return formatted_changes


def build_telegram_message(commit_info, changes):
    return f"""**New commit**
    
Repository: **{commit_info["repository"]}**
Branch: **{commit_info['branch']}**

Author: **{commit_info['author']}**
Date: **{commit_info['date']}**

{commit_info['message']}

**Changes**

{changes}

**[Link to the commit]({REPO_URL}/commit/{commit_info['hash']})**

__autogenerated message__
"""


def get_commit_info():
    commit_info = {
        'message': run_git_command(['git', 'log', '-1', '--pretty=%B']),
        'hash': run_git_command(['git', 'log', '-1', '--pretty=%H']),
        'date': run_git_command(['git', 'log', '-1', '--pretty=%ad', '--date=iso']),
        'author': run_git_command(['git', 'log', '-1', '--pretty=%an']),
        'branch': run_git_command(["git", "rev-parse", "--abbrev-ref", "HEAD"]),
        'repository': run_git_command(["basename -s .git `git remote get-url origin`"], use_shell=True)
    }
    return commit_info


def get_commit_changes(commit_hash):
    raw_changes = run_git_command(['git', 'show', '--stat', '--pretty=', commit_hash])
    if raw_changes:
        return format_commit_changes(raw_changes)
    return ""


def post_to_telegram(message):
    app = Client("post_commit")
    app.start()
    app.send_message(CHANNEL, message)
    app.stop()


def main():
    commit_info = get_commit_info()
    if not commit_info['message'].startswith("v"):
        logging.info("No new version commit detected, exiting.")
        return

    changes = get_commit_changes(commit_info['hash'])

    telegram_message = build_telegram_message(commit_info, changes)
    logging.info("Posting message to Telegram")
    post_to_telegram(telegram_message)


main()
