from pathlib import Path
import subprocess
import re
import logging
from pyrogram import Client

# Setup logging
logging.basicConfig(level=logging.INFO)

# Constants
PROJECT_FOLDER = Path(__file__).resolve().parent.parent.parent
CHANNEL = "@stewart_github"
REPO_URL = "https://github.com/ilyamiro/stewart"

with open(f"{PROJECT_FOLDER}/version.txt", "r", encoding="utf-8") as file:
    version = file.read()


# Utility Functions
def run_git_command(args, use_shell=False):
    try:
        result = subprocess.run(args, capture_output=True, text=True, shell=use_shell, check=True)
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        logging.error(f"Error running command {args}: {e}")
        return None


def replace_repeated_chars(input_string, char):
    pattern = f"{re.escape(char)}+"
    return re.sub(pattern, char, input_string)


def format_commit_changes(raw_changes):
    change_lines = raw_changes.strip().split("\n")
    formatted_changes = "\n".join([f"• {line.strip()}" for line in change_lines if line.strip()])

    # Apply repeated character replacements
    formatted_changes = replace_repeated_chars(formatted_changes, "+")
    formatted_changes = replace_repeated_chars(formatted_changes, "-")
    formatted_changes = replace_repeated_chars(formatted_changes, " ")
    return formatted_changes


def build_telegram_message(commit_info, changes):
    return f"""**New commit** 
Version: **{version}**
    
Repository: **{commit_info["repository"]}**
Branch: **{commit_info['branch']}**

Author: **{commit_info['author']}**
Date: **{commit_info['date']}**

{commit_info['message']}

{changes}

**[Link to the commit]({REPO_URL}/commit/{commit_info['hash']})**

__autogenerated message__
"""


def build_edit_message():
    return f"""Hello everyone! 

    My nickname is Ilya Miro, I am a 16 years old enthusiastic python developer with lots of motivation

    This telegram channel is intended to cover my progress of creating a virtual assistant named Stewart. I will post my progress, my daily tasks and demonstrations. Have a good day!😄

    Current project version: **{version}**

    GitHub (https://github.com/ilyamiro/Stewart)
    YouTube (https://youtube.com/@stewart.github)

    My telegram (http://t.me/sacrificeit)

    """


def get_commit_info():
    commit_info = {
        'message': run_git_command(['git', 'log', '-1', '--pretty=%B']),
        'hash': run_git_command(['git', 'log', '-1', '--pretty=%H']),
        'date': run_git_command(['git', 'log', '-1', '--pretty=%ad', '--date=iso']),
        'author': run_git_command(['git', 'log', '-1', '--pretty=%an']),
        'branch': run_git_command(["git", "rev-parse", "--abbrev-ref", "HEAD"]),
        'repository': run_git_command(["basename -s .git `git remote get-url origin`"], use_shell=True)
    }
    return commit_info


def get_commit_changes(commit_hash):
    raw_changes = run_git_command(['git', 'show', '--stat', '--pretty=', commit_hash])
    if raw_changes:
        return format_commit_changes(raw_changes)
    return ""


def main():
    commit_info = get_commit_info()
    if not commit_info['message'].startswith("v"):
        logging.info("No new version commit detected, exiting.")
        return

    changes = get_commit_changes(commit_info['hash'])

    telegram_message = build_telegram_message(commit_info, changes)
    logging.info("Posting message to Telegram")

    app = Client("post_commit")
    app.start()
    app.send_message(CHANNEL, telegram_message)
    app.edit_message_caption(CHANNEL, 4, build_edit_message())
    app.stop()


main()
