lang:
  prefix: en
  name: english
voice:
  sex: m
  ru:
    model: v4_ru
    m: eugene
    f: kseniya
  en:
    model: v3_en
    m: en_70
    f: en_76
startup:
  sound: data/sounds/startup.wav
module:
  dir: modules
trigger:
  triggers: [стюарт, стюард, stewart]
  trigger-mode: disabled # timed, disabled, enabled
  trigger-time: 25 # if trigger mode is timed, the amount of time it takes for VA to forget it was called
command-spec:
  no-multi-first-words-ru: ["найди", "найти", "запиши", "скажи", "ответь"]
  no-multi-first-words-en: ["find", "write", "answer"]
  connect-word-ru: "и"
  connect-word-en: "and"
gpt:
  state: off
  provider: You
  start-prompt-ru: "Отныне действуй как Стюарт, голосовой помощник. Стюарт всегда преобразует числа в их словесную форму, например, '29' становится 'двадцать девять', '18-й' становится 'восемнадцатый', а '3/4' становится 'три четверти'. Стюарт известен своими краткими ответами, обычно всего несколько слов или одно-два предложения. Стюарт также никогда не говорит, что ему было велено что-то делать. Начнем (не подтверждай)."
  start-prompt-en: "From now on, please act as Stewart, the voice assistant. Stewart always converts numbers into their word form, for example, '29' becomes 'twenty nine', '18th' becomes 'eighteenth', and '3/4' becomes 'three fourths'. Stewart is known for his brief responses, usually just a few words or a sentence or two. Stewart also never states that he was instructed to do anything. Let's begin (don't confirm)"
  start-answer-ru: "Как я могу вам помочь, сэр?"
  start-answer-en: "How can i help you, sir?"
answers-ru:
  startup:
    - "Конфигурация ядра завершена. Голосовой ассистент готов к работе"
    - "Загрузка успешно завершена. Чем могу быть полезен, сэр?"
  default:
    - "Я здесь, чтобы помочь вам, сэр"
    - "Чем могу быть полезен, сэр?"
  multi:
    - "Конечно, сэр"
    - "Уже выполняю, сэр"
    - "Безусловно, сэр"
answers-en:
  startup:
    - "Core configuration process ended. How can i assist you today?"
  default:
    - "I am at your service, sir"
    - "I am here to help, sir"
  multi:
    - "Processing your commands, sir"
    - "Yes, sir"
    - "Of course, sir"
commands:


# an example of commands distribution:
#employees:
#  - name: Alice
#    role: Developer
#    age: 28
#    department: Engineering
#
#  - name: Bob
#    role: Designer
#    age: 32
#    department: Design
#
#  - name: Charlie
#    role: Manager
#    age: 35
#    department: Management
