audio:
  stt:
    backend: vosk # Options: 'vosk', 'whisper'
    model: tiny # Model size ('tiny', 'base', 'small' for whisper; 'small' for vosk)
    speaker-recognition: false
    speech-mode-restricted: false
  tts:
    enable: true
    enable-caching: true
    engine: kokoro
    speed: 1.0
    en:
      f: af_heart
      m: am_adam
      sex: m
      lang_code: a
    ru:
      f: af_heart
      m: am_adam
      sex: m
      lang_code: a
lang:
  name: english
  prefix: en
plugins:
  core:
    music-download: false
    usb-default:
    - linux foundation
    - webcam
    - network
    - finger
settings:
  animation: true
  inactivity-threshold: 300
  max-history-length: 100
  react-no-command: false
  text-mode: false
  trigger:
    trigger-mode: enabled
    trigger-time: 30
start-up:
  sound-enable: true
  sound-path: data/sounds/startup.wav
  voice-enable: true
